CLOUD_SERVICE: "{{ .Values.global.cloud_store_provider }}"
PG_HOST: "{{ .Values.global.postgresql.host }}"
PG_USER: "{{ .Values.postgresqlUser | default .Values.global.postgresql.username }}"
PGPASSWORD: "{{ .Values.postgresqlPassword | default .Values.global.postgresql.password }}"
S3_BACKUP_BUCKET: "{{ .Values.global.postgresql_backup_cloud_bucket }}"
GS_BACKUP_BUCKET: "{{ .Values.global.postgresql_backup_cloud_bucket }}"
AWS_ACCESS_KEY_ID: "{{ .Values.global.s3_access_key }}"
AWS_SECRET_ACCESS_KEY: "{{ .Values.global.s3_secret_key }}"
AWS_ENDPOINT_URL: "{{ .Values.global.s3_endpoint_url }}"
AWS_DATA_PATH: "{{ .Values.global.s3_path_style_access }}"
AWS_DEFAULT_REGION: "{{ .Values.global.s3_signing_region }}"